space: dev-space
space-developer:
  users:
    - jsmith
    - adeveloper
  ldap_users: []
  saml_users: []
  ldap_groups:
    - CN=Tanzu-Devs,OU=Groups,DC=corp,DC=example,DC=com
  saml_groups: []

space-manager:
  users:
    - adeveloper
  ldap_users: []
  saml_users: []

space-auditor:
  users:
    - oldemployee
  ldap_users: []
  saml_users: []

space-supporter:
  users: []
  ldap_users: []
  saml_users: []
